name: Python Code Style

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "**.py"
  push:
    paths:
      - "pyproject.toml"
      - "**.py"

jobs:
  code-style-checks:
    name: Python Code Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3.1.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check imports
        uses: isort/isort-action@v1.1.0
      - name: Check formatting
        uses: psf/black@stable
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Linting (flake8)
        uses: py-actions/flake8@v2.2.1
