name: Coding Style & Unittests

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "**.py"
  push:
    paths:
      - "pyproject.toml"
      - "**.py"

jobs:
  code-style-checks:
    name: Test with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
